// This file was auto-generated by ML.NET Model Builder. 

using System;
using VNetML.Model;

namespace VNetML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Virtaama = 736F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Nousu with predicted Nousu from sample data...\n\n");
            Console.WriteLine($"Virtaama: {sampleData.Virtaama}");
            Console.WriteLine($"\n\nPredicted Nousu: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
