// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace VNetML.Model
{
    public class ModelInput
    {
        [ColumnName("nousu"), LoadColumn(0)]
        public float Nousu { get; set; }


        [ColumnName("vkorkeus"), LoadColumn(1)]
        public float Vkorkeus { get; set; }


        [ColumnName("ltila"), LoadColumn(2)]
        public float Ltila { get; set; }


        [ColumnName("virtaama"), LoadColumn(3)]
        public float Virtaama { get; set; }


    }
}
